### ISSUE TITLE
Change translation domain to something else?

### ISSUE THREAD

**Issue by erral** [plone/Products.validation#11]
Now for Plone 6.1 we have removed Products.validation sources from buildout.coredev:

https://github.com/plone/buildout.coredev/commit/f7457fc0abdd01691b60cfbc489600c58d92c4ac

This means that the script that updates the translations from the sources will not take those translations (and it will delete the pre-existing ones).

If we change the [translation domain](https://github.com/plone/Products.validation/blob/master/Products/validation/i18n.py#L8) from `plone` to something else, we will need to bring the translated strings from `plone.app.locales` to here. And then we have another package where the translations should be added.

This also means that we need to create a separate branch in `plone.app.locales` for Plone 6.0.x and 6.1.x, which is not bad and perhaps we will end up needing that.

Or, we can rollback the removal of Products.validation in buildout.coredev.

Any comment @mauritsvanrees @jensens ?

**Comment by mauritsvanrees** [comment]
Just checked for reference: the last release (2.1.3) was made at the time of Plone 5.2.2.  So no one is actively maintaining this package currently.

We could:

* Keep `plone` as domain.
* Copy the po files from `plone.app.locales` to here and cleanup.
* Release it as version 3.0.0 and use that version in coredev 6.0 and 6.1.

Then with the next plone.app.locales release, these translations could be removed, and users could just use the new `Products.validation` pin.

It would be good to have this package testable on its own first though.  I am looking at putting the `plone/meta` sauce over it, if that is not too hard.

**Comment by jensens** [comment]
collective.easyform is using the package, otherwise I don't know any consumers.
https://github.com/collective/collective.easyform/blob/45059eacb481f8dedb0b85f39b769fad562f1180/setup.py#L53

So we can not drop it. I am +/- 0 for keeping or renaming the i18ndomain - but +1 for the idea to copy the translation over here.

**Comment by mauritsvanrees** [comment]
See https://github.com/plone/Products.validation/pull/12 for my PR that makes the master branch for Plone 6.0 and 6.1 only.

**Comment by jensens** [comment]
> hat makes the master branch

While at it: rename to the branch to `main`?

**Comment by mauritsvanrees** [comment]
> > hat makes the master branch
> 
> While at it: rename to the branch to `main`?

Done, and coredev 6.0 `sources.cfg` updated.

**Comment by mauritsvanrees** [comment]
@erral Could you take care of moving the translations from `plone.app.locales` in here?

**Comment by erral** [comment]
yes, i will handle it next week

**Comment by erral** [comment]
See https://github.com/plone/Products.validation/pull/13
