### ISSUE TITLE
Still used?

### ISSUE THREAD

**Issue by gforcada** [plone/Products.validation#9]
I was spending some time applying `plone/meta` to this repository but after a while, I'm starting to think that this distribution is actually not used anymore in Plone? 🤔 

At least for Plone 6 it's not in `bin/instance` when running `buildout.coredev` default configuration.

- seems that no other distribution depends on it
- in `buildout.coredev` is only included in [`tests.cfg`](https://github.com/plone/buildout.coredev/blob/ab3fd70ed03d429b7f5d781a4d995ed4e048a6b4/tests.cfg#L110), but as no other distribution depends on it, it does not end up in `bin/instance`

I myself never used it, is it something that was more or less part of the Archetypes ecosystem? 🤔

Should we remove it from `buildout.coredev`? 🤔

**Comment by davisagli** [comment]
It doesn't depend on Archetypes, but it was typically used with Archetypes. Makes sense to me to remove it.

**Comment by gforcada** [comment]
@davisagli thanks I created https://github.com/plone/buildout.coredev/pull/854 to clean it up then 😄

**Comment by mauritsvanrees** [comment]
Is this not used by easyform still?

**Comment by mauritsvanrees** [comment]
Yes, easyform still has this in the [requirements](https://github.com/collective/collective.easyform/blob/4.1.2/setup.py#L52) and in `validators.py` it [imports it](https://github.com/collective/collective.easyform/blob/4.1.2/src/collective/easyform/validators.py#L6-L7) and [uses it](https://github.com/collective/collective.easyform/blob/4.1.2/src/collective/easyform/validators.py#L63).

It looks like it is intended to be optional, but then it would need to be in a `try/except ImportError` block.

It makes several [base validators](https://github.com/plone/Products.validation/blob/master/Products/validation/validators/BaseValidators.py) available, and I indeed see them when I add a field in a form and go to the advanced tab:

![Screenshot 2023-04-22 at 16 33 54](https://user-images.githubusercontent.com/210587/233790902-6ac94d51-831a-42b8-929d-870b09a07a12.png)

It might make sense to copy the relevant parts of `Products.validation` into `collective.easyform`.  Or reimplement the base validators as pure `z3c.form` validators.

So: yes it is still used, but not in core.
